######################################################################
# Automatically generated by qmake (3.0) ?? ???? 31 14:01:06 2014
######################################################################

QT += network xml

QT       -= gui

TEMPLATE = app
TARGET = test-qwebdav
INCLUDEPATH += .

# Input
HEADERS += qwebdav.h
SOURCES += qwebdav.cpp main.cpp
